# -*- coding: utf-8 -*-
"""crop_data_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzGMUv4eLRfCtmXIVTFh0eE0rzr-vwgZ
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("kashana/us-crop-data")

print("Path to dataset files:", path)

import pandas as pd
import os

# If you're not sure what the exact filename is, list the files:
print(os.listdir(path))

# Assuming the dataset has a file named "pollution_us_2000_2021.csv"
crop_data = pd.read_csv(os.path.join(path, "US_crop_data.csv"))

crop_data.head()

crop_data.shape[0]

crop_data.dropna()

crop_data.shape[0]

