# -*- coding: utf-8 -*-
"""pollution_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlDmbIFcLMdfE2b5PhC4axJrnWIiinOS
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("alpacanonymous/us-pollution-20002021")

print("Path to dataset files:", path)

import pandas as pd
import os

# If you're not sure what the exact filename is, list the files:
print(os.listdir(path))

# Assuming the dataset has a file named "pollution_us_2000_2021.csv"
pollution_df = pd.read_csv(os.path.join(path, "pollution_2000_2021.csv"))

pollution_df.head()

value_cols = [
    c for c in pollution_df.columns
    if c.endswith("Mean") or c.endswith("AQI")
]

to_keep = [
    "Date", "Year", "Month", "Day",
    "State", "County", "City"
] + value_cols

def month_to_season(m):
    if m in (12, 1, 2):
        return "Winter"
    elif m in (3, 4, 5):
        return "Spring"
    elif m in (6, 7, 8):
        return "Summer"
    else:
        return "Fall"

clean_df = pollution_df[to_keep].copy()

clean_df["Season"] = clean_df["Month"].apply(month_to_season)

clean_df.head()

row_count = len(clean_df)
row_count

clean_df = clean_df.dropna()

row_count = len(clean_df)
row_count