# -*- coding: utf-8 -*-
"""temperature_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3ZZfDNJCs7bkVd3Ov-MgLmBfV9wBI4Z
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("justinrwong/average-monthly-temperature-by-us-state")

print("Path to dataset files:", path)

import pandas as pd
import os

# If you're not sure what the exact filename is, list the files:
print(os.listdir(path))

# Assuming the dataset has a file named "pollution_us_2000_2021.csv"
temperatures_df = pd.read_csv(os.path.join(path, "average_monthly_temperature_by_state_1950-2022.csv"))

temperatures_df.head()

cols_to_drop = [col for col in temperatures_df.columns
                if col.startswith('Unnamed') or col == 'monthly_mean_from_1901_to_2000']
clean_temps_df = temperatures_df.drop(columns=cols_to_drop)

clean_temps_df = clean_temps_df.dropna().reset_index(drop=True)

clean_temps_df.head()