# -*- coding: utf-8 -*-
"""temperature_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3ZZfDNJCs7bkVd3Ov-MgLmBfV9wBI4Z
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("justinrwong/average-monthly-temperature-by-us-state")

print("Path to dataset files:", path)

import pandas as pd
import os

print(os.listdir(path))

temperatures_df = pd.read_csv(os.path.join(path, "average_monthly_temperature_by_state_1950-2022.csv"))

temperatures_df.head()

cols_to_drop = [col for col in temperatures_df.columns
                if col.startswith('Unnamed') or col == 'monthly_mean_from_1901_to_2000']
clean_temps_df = temperatures_df.drop(columns=cols_to_drop)

clean_temps_df = clean_temps_df.dropna().reset_index(drop=True)

clean_temps_df.head()

# Define a function to map month to season
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'

clean_temps_df['season'] = clean_temps_df['month'].map(get_season)

clean_temps_df.head()

from sqlalchemy import create_engine

host     = 'database-1.cyljtjkkhdgh.us-east-1.rds.amazonaws.com'
dbname   = 'postgres'
user     = 'postgres'
password = 'database1234'
port     = 5432

engine = create_engine(
    f'postgresql://{user}:{password}@{host}:{port}/{dbname}'
)

# Push your cleaned DataFrame
clean_temps_df.to_sql(
    'temperature_data',
    engine,
    if_exists='replace',
    index=False
)
